name: innovation
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.2
  app_links: ^7.0.0
  google_fonts: ^8.0.2
  flutter_appauth: ^7.0.0
  http: ^1.2.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
